on:
  workflow_dispatch:
    inputs:
      fail:
        description: 'Set true to fail the workflow.'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: >
          sleep 3s
      - run: |
          if ${{ inputs.fail }}
          then
            exit 1
          else
            exit 0
          fi
